import 'package:flutter/material.dart';
import 'package:waste_water_app/components/info_expansion_tile.dart';

class InfoPage extends StatelessWidget {
  InfoPage({Key? key}) : super(key: key);
  List wasteWaterContaminants = [
    {
      "title": "Domestic Wastewater",
      "content":
          "This type of wastewater comes from households and includes water from toilets, sinks, showers, washing machines, and other residential sources."
    },
    {
      "title": "Industrial Wastewater",
      "content":
          "Industrial processes generate wastewater that can contain a wide range of pollutants depending on the industry. Common contaminants include chemicals, heavy metals, oils, and various by-products of manufacturing and production processes."
    },
    {
      "title": "Agricultural Wastewater",
      "content":
          "Agriculture can contribute to wastewater through the use of fertilizers, pesticides, and irrigation practices that can carry pollutants into surface and groundwater."
    },
    {
      "title": "Stormwater Runoff",
      "content":
          "When rainwater or snowmelt flows over roads, parking lots, and other surfaces, it can pick up pollutants such as oils, sediment, and chemicals, becoming stormwater runoff that can contribute to wastewater."
    },
  ];

  List sections = [
    {
      "heading": "What is Wastewater",
      "desc":
          "Wastewater is water that has been used and contaminated by various human activities, industrial processes, or natural processes. It includes any water that has been affected in quality by human interactions or natural phenomena, making it unsuitable for immediate use or consumption. Wastewater typically contains a variety of impurities, pollutants, and contaminants, which can include:",
      "subtopics": [
        {
          "title": "Domestic Wastewater",
          "content":
              "This type of wastewater comes from households and includes water from toilets, sinks, showers, washing machines, and other residential sources."
        },
        {
          "title": "Industrial Wastewater",
          "content":
              "Industrial processes generate wastewater that can contain a wide range of pollutants depending on the industry. Common contaminants include chemicals, heavy metals, oils, and various by-products of manufacturing and production processes."
        },
        {
          "title": "Agricultural Wastewater",
          "content":
              "Agriculture can contribute to wastewater through the use of fertilizers, pesticides, and irrigation practices that can carry pollutants into surface and groundwater."
        },
        {
          "title": "Stormwater Runoff",
          "content":
              "When rainwater or snowmelt flows over roads, parking lots, and other surfaces, it can pick up pollutants such as oils, sediment, and chemicals, becoming stormwater runoff that can contribute to wastewater."
        },
      ]
    },
    {
      "heading": "Industrial Wastewater",
      "desc":
          "Industrial wastewater refers to the contaminated water generated by industrial and manufacturing processes. It is a significant component of overall wastewater and can be particularly challenging to manage due to the wide range of contaminants it may contain. Industrial wastewater is produced by a broad spectrum of industries, including chemical manufacturing, petrochemicals, textiles, food and beverage processing, mining, metalworking, pulp and paper production, pharmaceuticals, and more. Each industry generates wastewater with unique characteristics and contaminants.\nContaminants: Industrial wastewater can contain a variety of pollutants, depending on the processes involved. Common contaminants include:",
      "subtopics": [
        {
          "title": "Chemicals",
          "content":
              "Many industrial processes use chemicals that can find their way into wastewater. These chemicals may include solvents, acids, bases, and heavy metals."
        },
        {
          "title": "Organic Compounds",
          "content":
              "Organic pollutants such as oils, greases, and organic solvents are often present in industrial wastewater."
        },
        {
          "title": "Suspended Solids",
          "content":
              "Solid particles like sediment, sludge, and particulate matter can be suspended in industrial wastewater."
        },
        {
          "title": "Nutrients",
          "content":
              "In some cases, excess nutrients like nitrogen and phosphorus can be present, which can lead to water quality issues in receiving bodies of water."
        },
      ],
    },
    {
      "heading": "Treatment",
      "desc":
          "Wastewater treatment is a process that involves the removal of contaminants, pollutants, and impurities from wastewater to make it safe for discharge into the environment or for reuse. The treatment methods employed can vary depending on the type and complexity of the wastewater and the desired level of treatment. Here are some common methods and stages of wastewater treatment:",
      "subtopics": [
        {
          "title": "Preliminary Treatment",
          "content":
              "Screening: The wastewater is passed through screens or grates to remove large objects like sticks, leaves, and plastic."
        },
        {
          "title": "Primary Treatment",
          "content":
              "Sedimentation: Wastewater is allowed to sit in large tanks, allowing solids to settle at the bottom. This process removes a significant portion of suspended solids and organic matter."
        },
        {
          "title": "Secondary Treatment",
          "content":
              "Biological Treatment: Wastewater is treated by microorganisms that break down organic pollutants. Common methods include:\nActivated Sludge Process: Wastewater is mixed with microorganisms (activated sludge) in aeration tanks.\nTrickling Filters: Wastewater is distributed over beds of rocks or plastic media where microorganisms attach and break down organic matter.\nSequential Batch Reactors (SBR): Aeration and settling phases are alternated in a single tank to treat wastewater."
        },
        {
          "title": "Tertiary Treatment (Advanced Treatment)",
          "content":
              "Filtration: Wastewater is passed through sand, gravel, or membrane filters to further remove remaining fine solids and pathogens.\nChemical Treatment: Chemicals like chlorine, ozone, or ultraviolet (UV) light are used to disinfect and remove residual contaminants.\nNutrient Removal: Additional treatment steps may be used to remove excess nutrients like nitrogen and phosphorus, often to prevent eutrophication of receiving waters."
        },
        {
          "title": "Disinfection",
          "content":
              "After primary, secondary, and tertiary treatments, wastewater is often disinfected to kill any remaining pathogenic microorganisms before discharge. Chlorination, UV disinfection, and ozonation are common methods."
        },
        {
          "title": "Sludge Treatment",
          "content":
              "Solid materials collected during primary and secondary treatment, known as sludge, are treated separately. Methods include:\nAnaerobic Digestion: Bacteria break down organic matter in the absence of oxygen, producing biogas (methane).\nAerobic Digestion: Microorganisms decompose organic materials in the presence of oxygen.\nDewatering: Sludge is mechanically or chemically treated to remove water, reducing volume for disposal.\nIncineration: In some cases, sludge can be incinerated to reduce volume and generate energy."
        },
      ]
    },
    {
      "heading": "Zero Liquid Discharge (ZLD)",
      "desc":
          "ZLD stands for 'Zero Liquid Discharge.' It is an industrial water treatment process or approach designed to minimize or completely eliminate the discharge of wastewater from a manufacturing or industrial process. In a ZLD system, the goal is to recover and reuse as much water as possible from the industrial processes and treat the remaining wastewater to a point where there is no liquid discharge, hence the name 'Zero Liquid Discharge'.\n\nThe ZLD process is being widely adopted by numerous industries. It typically involves a combination of various technologies such as reverse osmosis, evaporation, crystallization, and other advanced water treatment methods to separate the water from the dissolved solids and pollutants. The treated water can then be reused within the industrial facility, reducing the need for fresh water intake and minimizing environmental impact.\n\nZLD is particularly important in industries where water is a scarce resource or where strict environmental regulations govern wastewater discharge. Recently, Maharashtra Government is imposing regulations on chemical industries, wherein ZLD is mandatory. This has already been implemented in the Khalapur industrial area.",
      "subtopics": []
    }
  ];
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          for (var i in sections)
            infoSection(i["heading"], i["desc"], i["subtopics"])
        ],
      ),
    );
  }

  Widget infoSection(String heading, String desc, List subtopics) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          heading,
          style: const TextStyle(fontSize: 32, fontWeight: FontWeight.bold),
        ),
        const SizedBox(
          height: 24,
        ),
        Text(
          desc,
          style: const TextStyle(fontSize: 17),
        ),
        const SizedBox(
          height: 15,
        ),
        for (var i in subtopics) infoExpansionTile(i['title'], i['content']),
        const SizedBox(
          height: 30,
        ),
      ],
    );
  }
}
